language: ruby
rvm:
  - 2.1.10
  - 2.2.10
  - 2.3.8
  - 2.4.7
  - 2.5.6
  - 2.6.4
services:
  - postgresql
gemfile:
  - gemfiles/rails_4.gemfile
  - gemfiles/rails_5.gemfile
  - gemfiles/rails_5_2.gemfile
  - gemfiles/rails_6_0.gemfile
before_script:
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:create
script:
  - bundle
  - bundle exec rspec
matrix:
  exclude:
    - rvm: 2.1.10
      gemfile: gemfiles/rails_5.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails_5_2.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails_6_0.gemfile
    - rvm: 2.2.10
      gemfile: gemfiles/rails_5_2.gemfile
    - rvm: 2.2.10
      gemfile: gemfiles/rails_6_0.gemfile
    - rvm: 2.3.8
      gemfile: gemfiles/rails_6_0.gemfile
    - rvm: 2.4.7
      gemfile: gemfiles/rails_6_0.gemfile
